/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Persondesc;
import model.Persondeschistory;
import model.Vitaldesc;
import model.Vitaldeschistory;








/**
 *
 * 
 */
public class AnalyseCommunity extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Persondeschistory history;
    Vitaldeschistory vitalhistory;
     //public static final String[] com = {"Street1", "Street2"};
    public AnalyseCommunity(Persondeschistory history,Vitaldeschistory vitalhistory) {
        initComponents();
        this.history = history;
        this.vitalhistory = vitalhistory;
          tblvital.setShowVerticalLines(true);
          //  tblencount.setShowVerticalLines(true);
       // populateTable();
       commpopulateTable();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblvital = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(691, 542));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblvital.setBackground(new java.awt.Color(204, 255, 204));
        tblvital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Selobj", "Community", "Normal SBP", "Abnormal SBP", "Normal DBP", "Abnormal DBP"
            }
        ));
        jScrollPane1.setViewportView(tblvital);
        if (tblvital.getColumnModel().getColumnCount() > 0) {
            tblvital.getColumnModel().getColumn(0).setMinWidth(20);
            tblvital.getColumnModel().getColumn(0).setMaxWidth(20);
            tblvital.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblvital.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblvital.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 685, 127));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setText("Community Wise Analysis of BP Vitals");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 685, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/akhil_kaundinya/Downloads/bp4.png")); // NOI18N
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 550, 210));
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblvital;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model =(DefaultTableModel) tblvital.getModel();
   
    
    // System.out.println("hello"+vs.get(0));
    
    
   model.setRowCount(0);
   
  
 for( Persondesc vs: history.getHistory())
       {
     Object[] row= new Object[7];
//     
  row[0]= vs;
 // System.out.println("hellosize"+vs.getseats());
//String s=cmbmanufacture.getItemAt(vs.getManufacturer());

   row[1]=vs.getId();
   row[2]=vs.getPname();
   row[3]=vs.getAddress();
   row[4]=vs.getCommunity();
   row[5]=vs.getAge();
   // row[2]=cmbmodel.getItemAt(vs.getModelno());
   
  // row[3]=cmbseat.getItemAt(vs.getSeats());
  // row[3]=vs.getSeats();
  // row[4]=vs.getQty_available();
   // row[5]=cmbcity.getItemAt(vs.getCity());
  //  row[6]=vs.getFleet();
    model.addRow(row);
   }
    }
    //encounterpopulate
     
     private void commpopulateTable() {
        DefaultTableModel model =(DefaultTableModel) tblvital.getModel();
   int i;
   int found;
    //new code starts
   // String[] distinctcomm =new String[10];
   String[] distinctcomm = new String[20] ;
    distinctcomm[0]="x";
  //  var distinctcomm =[];
   // String distinctcomm = [];
   //int alength= histo;
    //for (var i = 0; i < array.length; i++)
    found=0;
     for( Persondesc vs: history.getHistory())
       {System.out.println("hello"+vs.getCommunity());
       String comm=vs.getCommunity();
       int icomm=distinctcomm.length;
       for(i=0;i<icomm;i++)
       {if(distinctcomm[i]==null)
       {break;}
       else
           if(distinctcomm[i].equals(comm))
           {found=1;
           }
       }
        if(found==0)
       {distinctcomm[i]=comm;
       System.out.println("added");
       }
       }
    
     /*int pid;
     int vid;
     int personcount=0;
     int patientcount=0;
     int nsbp;
     int ndbp;
     int asbp;
     int adbp;
     String pcomm;
      model.setRowCount(0);
    for(int j=1;j<distinctcomm.length;j++)    
    { String commname=distinctcomm[j];
    if(commname==null)
    { break;}
    else
    {
        // System.out.println("dist comm name="+commname);   
     nsbp=0;
     ndbp=0;
     asbp=0;
      adbp=0;
     // int sbp=0;
    // int dbp=0;
     for( Persondesc vs: history.getHistory())
     {  pcomm=vs.getCommunity();
        pid=vs.getId();
        System.out.println("person=" +pcomm+"id="+pid);
    int  Patientfound=0;
     if(pcomm.equals(commname))
     {
     int sbp=0;
     int dbp=0;
     personcount++;
     String vcomm;
    //  System.out.println("1=sbp="+sbp+"dbp="+dbp+"nsbp="+nsbp+"asbp="+adbp+"ndbp="+ndbp+"adbp="+adbp);
      
       for( Vitaldesc vs1: vitalhistory.getvitalHistory())
       {vid=vs1.getId();
           if(vid==pid)
           {sbp=vs1.getSp();
           dbp=vs1.getDp();
           Patientfound=1;
           }
       }//for vital loop
       if(sbp>120) asbp++; else nsbp++;
       if(dbp<80) adbp++; else ndbp++;
      // System.out.println("2=sbp="+sbp+"dbp="+dbp+"nsbp="+nsbp+"asbp="+asbp+"ndbp="+ndbp+"adbp="+adbp);
       patientcount++;
     }//if pcomm equals
     }//for person loop
     
  // }
   //DefaultTableModel model1 =(DefaultTableModel) tblencount.getModel();
   
    
    // System.out.println("hello"+vs.get(0));
    
    
  
    Object[] row= new Object[7];
//     
  //row[0]= 0;
 // System.out.println("hellosize"+vs.getseats());
//String s=cmbmanufacture.getItemAt(vs.getManufacturer());

   row[1]=commname;
   row[2]=nsbp;
   row[3]=asbp;
   row[4]=ndbp;
   row[5]=adbp;
  // row[6]=vs.getCity();
  
    model.addRow(row);
    }
    }//distinct loop
      
       
      // if(vs.getCommunity() not in distintcomm)
     // ArrayUtils.*/
     int pid;
     int vid;
     int personcount=0;
     int patientcount=0;
     int nsbp;
     int ndbp;
     int asbp;
     int adbp;
     String pcomm;
      model.setRowCount(0);
    for(int j=1;j<distinctcomm.length;j++)    
    { String commname=distinctcomm[j];
    if(commname==null)
    { break;}
    else
    {
        // System.out.println("dist comm name="+commname);   
     nsbp=0;
     ndbp=0;
     asbp=0;
      adbp=0;
      patientcount=1;
      //personcount=1;
     // int sbp=0;
    // int dbp=0;
     for( Persondesc vs: history.getHistory())
     {  pcomm=vs.getCommunity();
        pid=vs.getId();
        System.out.println("person=" +pcomm+"id="+pid);
    int  Patientfound=0;
     if(pcomm.equals(commname))
     {
     int sbp=0;
     int dbp=0;
     personcount++;
     String vcomm;
    //  System.out.println("1=sbp="+sbp+"dbp="+dbp+"nsbp="+nsbp+"asbp="+adbp+"ndbp="+ndbp+"adbp="+adbp);
      
       for( Vitaldesc vs1: vitalhistory.getvitalHistory())
       {vid=vs1.getId();
           if(vid==pid)
           {sbp=vs1.getSp();
           dbp=vs1.getDp();
           Patientfound=1;
           }
          // patientcount++;
       }//for vital loop
       if(Patientfound==1)
       {
       if(sbp>120) asbp++; else nsbp++;
       if(dbp<80) adbp++; else ndbp++;
       patientcount++;
       }
      // System.out.println("2=sbp="+sbp+"dbp="+dbp+"nsbp="+nsbp+"asbp="+asbp+"ndbp="+ndbp+"adbp="+adbp);
      //earlier patientcount++;
     }//if pcomm equals
     }//for person loop
     
  // }
   //DefaultTableModel model1 =(DefaultTableModel) tblencount.getModel();
   
    
    // System.out.println("hello"+vs.get(0));
    
    
  
    Object[] row= new Object[7];
//     
  //row[0]= 0;
 // System.out.println("hellosize"+vs.getseats());
//String s=cmbmanufacture.getItemAt(vs.getManufacturer());

   row[1]=commname;
   row[2]=nsbp;
   row[3]=asbp;
   row[4]=ndbp;
   row[5]=adbp;
  // row[6]=vs.getCity();
  
    model.addRow(row);
    }
    System.out.println("percount="+personcount+"patcount="+patientcount);
    }//distinct loop
      
       
      // if(vs.getCommunity() not in distintcomm)
     // ArrayUtils.
    
              
                      
      
  
    }
    
     //searchtable ends
       //sbpearchtable
     
    
     //searchtable ends
       //dbpsearchtable
     
     
     //searchtable ends
       //agesearchtable
     
     
     //searchtable ends
   // @Override
//public void setValueAt(Object value, int row, int col) {

//}
     //System.out.println("personcount" + personcount + "patientcount" + patientcount );
}
