/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Persondesc;
import model.Persondeschistory;

/**
 *
 * 
 */

public class createpanel extends javax.swing.JPanel {

    /**
     * Creates new form createpanel
     * @param history
     */
    Persondeschistory history;
    
     public static final String[] com = {"Street1", "Street2"};
    
    public createpanel(Persondeschistory history) {
        initComponents();
        this.history = history;
       
      
        var now = new Date();
       // DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
         DateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
  //  System.out.println("date is " + df.format(currentDate));
      //  var now = new Date();
        //now=df.format(now);
        txtfleet.setText(df.format(now));
       // System.out.println("seats"+now.toString());
        //txtfleet.setText(now.toString());
       // txtfleet=now.toSnowtring();
       
    }
    

    createpanel(JPanel workArea, Persondeschistory history) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcomm = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        lblage = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfleet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtcomm = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        btnhome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setAlignmentX(10.5F);
        setPreferredSize(new java.awt.Dimension(1758, 1457));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcomm.setText("Community");
        add(lblcomm, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 163, -1, 20));

        lbladdress.setText("Address");
        add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 258, 55, -1));

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        txtaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaddressKeyReleased(evt);
            }
        });
        add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 251, 184, 30));

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 424, 118, -1));

        lblage.setText("Age");
        add(lblage, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 212, -1, -1));

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
        });
        add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 207, 184, -1));

        lblcity.setText("City");
        add(lblcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 306, -1, -1));

        jLabel5.setText("Registered on");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 353, -1, -1));

        txtfleet.setEnabled(false);
        txtfleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfleetActionPerformed(evt);
            }
        });
        add(txtfleet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 345, 184, 33));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setText("Register Person");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 30, 567, -1));

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 79, -1, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 74, 184, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 127, 17, -1));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 122, 184, -1));
        add(txtcomm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 184, -1));

        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcityKeyPressed(evt);
            }
        });
        add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 301, 184, -1));

        btnhome.setBackground(new java.awt.Color(0, 153, 255));
        btnhome.setText("Home");
        add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/akhil_kaundinya/Downloads/bpmachine.jpg")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/akhil_kaundinya/Downloads/syring.jpg")); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 110, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        int stop=0;
     if(txtname.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid name");
         stop=1;
     }
     if(txtaddress.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid address");
         stop=1;
     }
     if(txtcity.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid city name");
         stop=1;
     }
     if(txtcomm.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid communityname");
         stop=1;
     }
     if(txtage.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid age");
         stop=1;
     }
     if(txtid.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this, "Please enter valid ID");
         stop=1;
     }
     
     // System.out.println("model"+model);
     //String fleet_update = txtfleetupdate.getText();
   //  int qty_available=10;
    // date exp_certificate;
    int serial=0;
      String address=txtaddress.getText();
        //serial=txtserial.getText();
        String community=txtcomm.getText();
        String city=txtcity.getText();
        String pname=txtname.getText();
    
    int age=0;
    if(!txtage.getText().isBlank())
    {
    age=Integer.parseInt(txtage.getText());
    }
   int id=0;
    if(!txtage.getText().isBlank())
    {
     id=Integer.parseInt(txtid.getText());
    }
   var now = new Date();
       // DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        // DateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
  //  System.out.println("date is " + df.format(currentDate));
      //  var now = new Date();
        //now=df.format(now);
       //txtfleet.setText(df.format(now));
        Date fleet=now;
 if(stop==0)  
 {
Persondesc md= history.addnewdesc();
md.setCommunity(community);
md.setAddress(address);
md.setAge(age);
md.setPname(pname);
md.setCity(city);
md.setId(id);

JOptionPane.showMessageDialog(this,"new Person added");
 }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddressKeyReleased
        // TODO add your handling code here:
         // String SNum =txtaddress.getText();
        //if(PhoneNo.matches("^[0-9]*$") && PhoneNo.length()==10)
        //if((SNum.matches("^[0-9]*$")) && (SNum.length()<12) )
        //{
        //    txtaddress.setBackground(Color.yellow);
            //JOptionPane.showMessageDialog(null,"You Have Entered Correct PhoneNO");
        //}
       // else
       
       // {txtaddress.setBackground(Color.blue);
         //   JOptionPane.showMessageDialog(null,"Please Enter Correct Unique ID No.");
        //}
    }//GEN-LAST:event_txtaddressKeyReleased

    private void txtfleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfleetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfleetActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
        String id =txtid.getText();
        //if(PhoneNo.matches("^[0-9]*$") && PhoneNo.length()==10)
        if((id.matches("^[0-9]*$")) && (id.length()<11) )
        {
            //txtid.setBackground(Color.yellow);
            //JOptionPane.showMessageDialog(null,"You Have Entered Correct PhoneNO");
        }
        else
       
        {
            //txtid.setBackground(Color.blue);
            JOptionPane.showMessageDialog(null,"Please Enter Correct ID");
            txtid.setText("");
        }
    }//GEN-LAST:event_txtidKeyPressed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
        // TODO add your handling code here:
        String age =txtage.getText();
        //if(PhoneNo.matches("^[0-9]*$") && PhoneNo.length()==10)
        if((age.matches("^[0-9]*$")) && (age.length()<4) )
        {
            //txtage.setBackground(Color.yellow);
            //JOptionPane.showMessageDialog(null,"You Have Entered Correct PhoneNO");
        }
        else
       
        {
            //txtage.setBackground(Color.blue);
            JOptionPane.showMessageDialog(null,"Please Enter Correct Age");
            txtage.setText("");
        }
    }//GEN-LAST:event_txtageKeyPressed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        String name =txtname.getText();
        Pattern pattern = Pattern.compile(new String ("^[a-zA-Z\\s]*$"));
        Matcher matcher = pattern.matcher(name);
    if(matcher.matches())
    {
         //if pattern matches
        //txtName.setBackground(Color.yellow);
    }
    else
    {
         //if pattern does not matches
        //txtName.setBackground(Color.orange);
            JOptionPane.showMessageDialog(null,"Please Enter your Correct Name");
            txtname.setText("");
    }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtcityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyPressed
        // TODO add your handling code here:
        String city =txtcity.getText();
        Pattern pattern = Pattern.compile(new String ("^[a-zA-Z\\s]*$"));
        Matcher matcher = pattern.matcher(city);
    if(matcher.matches())
    {
         //if pattern matches
        //txtName.setBackground(Color.yellow);
    }
    else
    {
         //if pattern does not matches
        //txtName.setBackground(Color.orange);
            JOptionPane.showMessageDialog(null,"Please Enter Correct City");
            txtcity.setText("");
    }
    }//GEN-LAST:event_txtcityKeyPressed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcomm;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcomm;
    private javax.swing.JTextField txtfleet;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
