/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Annapurna
 */
public class tabletry extends javax.swing.JPanel {

    /**
     * Creates new form tabletry
     */
          

    public tabletry() {
        initComponents();
        
       DefaultTableModel model2 =(DefaultTableModel) tbltry.getModel();   
       tbltry.setShowVerticalLines(true);
        model2.setRowCount(0);
         Object[] data0 = {"Normal", "Less Than 120", "and","Less Than 80"};
          model2.addRow(data0);
           Object[] data1 = {"Elevated", "120-129", "and","Less Than 80"};
          model2.addRow(data1);
           Object[] data2 = {"High BP Stage-1", "130-139", "or","80-89"};
          model2.addRow(data2);
          Object[] data3 = {"High BP Stage-2", "140 or Higher", "or","90 or higher"};
          model2.addRow(data3);
          Object[] data4 = {"High BP Emergency", "Higher than 180", "and/or","higher than 120"};
          model2.addRow(data4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbltry = new javax.swing.JTable();

        tbltry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltry);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltry;
    // End of variables declaration//GEN-END:variables
}
